<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>BLTools.core</AssemblyName>
    <RootNamespace>BLTools.core</RootNamespace>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Authors>Luc Bolly</Authors>
    <Company>Luc Bolly</Company>
    <Description>A library of various extensions and utilities for .NET</Description>
    
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Logging\LoggerMessages\**" />
    <Compile Remove="Security\Encryption\Asymmetric\**" />
    <EmbeddedResource Remove="Logging\LoggerMessages\**" />
    <EmbeddedResource Remove="Security\Encryption\Asymmetric\**" />
    <None Remove="Logging\LoggerMessages\**" />
    <None Remove="Security\Encryption\Asymmetric\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Diagnostic\TraceInfo.cs" />
    <Compile Remove="Diagnostic\TraceInfo_Build.cs" />
    <Compile Remove="Diagnostic\TraceInfo_Support.cs" />
    <Compile Remove="Logging\LoggerHelper.cs" />
  </ItemGroup>

</Project>
